project_id = "ghqjntefllyrqtmtivaw"

[functions.save-registration]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.test-mongodb-connection]
verify_jwt = false